### ISSUE TITLE
Number max of clients

### ISSUE THREAD

**Issue by Kiskuit** [maximouth/PR#1]
J'ai mal compris le troisième argument de listen, il donne pas un nombre max de clients, mais une taille max pour la file de demande. Du coup, il faut remettre un compteur (et le mutex qui va avec). Désolé ^^'

**Comment by maximouth** [comment]
Ah X)
Bon ba je vais rajouter ça alors :p
C'est juste du copié collé de mon ancienne version :p

Le 9 déc. 2016 23:32, "Kiskuit" <notifications@github.com> a écrit :

J'ai mal compris le troisième argument de listen, il donne pas un nombre
max de clients, mais une taille max pour la file de demande. Du coup, il
faut remettre un compteur (et le mutex qui va avec). Désolé ^^'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/maximouth/PR/issues/1>, or mute the thread
